### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by eudaimos** [skgdev/socket.io-msgpack-javascript#15]
I have tried following the instructions in the README as well as manipulating both the client connection and server connection and nothing seems to work.

When it does not blow up with a problem, the best I can get is a constant reconnection and the 

Socket.IO server version: `4.6.1`
`@skgdev/socket.io-msgpack-javascript` version: `1.2.0`

*Server*

```js
import { Server } from "socket.io";
import { build } from '@skgdev/socket.io-msgpack-javascript';

const io = new Server(3000, {
  serveClient: false,
  parser: customParser,
  cors: environment.cors,
  maxHttpBufferSize: 3.2e8,
});

io.on("connection", (socket) => {
  console.log('connected:', socket.id);
  setTimeout(() =>
    socket.emit('hello', { say: 'hello world!'}),
    2000,
  );
  socket.on('error', err => console.error('socket:', err));
  socket.on('disconnecting', (reason, desc) => console.log({ reason, desc }));
  socket.on('disconnect', (reason, desc) => console.log('disconnect:', { reason, desc }));
});
io.on('error', console.error);
```

Socket.IO client version: `4.6.1`
`@skgdev/socket.io-msgpack-javascript` version: `1.2.0`

*Client*

```js
import { io } from "socket.io-client";
import { build } from '@skgdev/socket.io-msgpack-javascript';

const socket = io("ws://localhost:3000/", {
  withCredentials: true,
  parser: customParser,
  // transports: ["websocket"] // uncomment for websocket-only transport
});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
});

socket.on('disconnect', (reason, desc) => console.log({ reason, desc }));
```

**Expected behavior**
Whether specifying `transports` option or not on the client, the socket will connect, perform the handshake successfully and messages will be passed back and forth in binary encoding.

**Platform:**
 - Device: MacBook Pro 2020 M1
 - OS: MacOS Ventura 13.2.1
 - Browser: Chrome

**Additional Context**
I tried using the example code from the README for the client which is:
```javascript
const socket = ioc('ws://localhost:' + PORT, {
  parser: customParser
});
```
which just bricks b/c socket.io complains that `customParser.Encoder` is **not** a function.

I tried marking the package as external for webpack and esbuild.

I tried importing using `require()` instead and no difference.

I tried importing as:
```javascript
import customParser from '@skgdev/socket.io-msgpack-javascript';
```
instead of just importing `build` and no difference.

I looked at the code and it appears to have the exact same implementation and interface as the msgpack parser maintained by the socket.io team so I don't understand what is wrong.

**Comment by georgiosgiatsidis** [comment]
I tried to reproduce the issue locally (by copying your code sample) and my client kept attempting to reconnect.
The on-disconnect error was `websocket connection closed`.

I managed to establish a connection by including the ignoreUndefined option in the encoder. However, I am not sure why this is happening. Needs more investigation.

```js
import msgPackParser from '@skgdev/socket.io-msgpack-javascript';
msgPackParser.build({ encoder: { ignoreUndefined: true }, decoder: {} });
```

Additionally, the ES module file is not listed in the `files` property of the package.json file. So, if you use the es module instead of the common js, you may experience issues.
We will include the 'es' module file in the next release (#14).

**Comment by nmargaritis** [comment]
@eudaimos Did you try @georgiosgiatsidis suggestion?

I will give it a go this week most probably and let you know.

**Comment by eudaimos** [comment]
thanks @georgiosgiatsidis - I tried your solution and it works.

AND I was able to import using the following both server and client and it works:
```javascript
import { build } from '@skgdev/socket.io-msgpack-javascript';
```

**Comment by nmargaritis** [comment]
Probably the new client of socket.io by default includes data in the handshake that come with undefined values and that's something that msgpack only supports via the ignoreUndefined flag. I think we can close this issue for now.
