### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by spitliner** [skgdev/socket.io-msgpack-javascript#16]
Hello, is there are any interested in support Typescript for this package?

**Comment by georgiosgiatsidis** [comment]
Hello, yes, it's planned to migrate to TypeScript soon.

**Comment by spitliner** [comment]
@georgiosgiatsidis I did write a typescript version a while back, do you mind I open a pull request and check it?

**Comment by georgiosgiatsidis** [comment]
Of course !

**Comment by nmargaritis** [comment]
Resolved via #17
